"""
Stage 2 transformer: converts the 3-level MultiIndex DataFrame from Stage 1
into the flat, encoded, imputed DataFrame expected by Stage 3 (factor analysis).

Replicates the feature engineering from notebooks 1.1.1 and 2.1:
  - Flattens MultiIndex to flat column names
  - Merges compound columns (exercise, caffeine, naps, sleepiness, dreams, nightmares)
  - Computes sw_9am_start_diff and sw_5pm_end_diff from datetime columns
  - One-hot encodes RLS probability
  - Selects the ~130 columns used in the final factor analysis iteration
  - Encodes sex, exercise, naps, daytime sleepiness, dream recall
  - Converts boolean columns to int
  - Replaces placeholder values (-55, -66) with NA
  - Drops rows missing AHI
  - Imputes (median for numeric, mode for categorical)
  - One-hot encodes dream_recall_frequency (drop first)

generated by claude opus 4.6 based on the 1.1.1 and 2.1 notebooks.
"""

import numpy as np
import pandas as pd
from pathlib import Path


# ── Column mapping: (descriptive, original_id) → flat_name ──────────────────
# Built from the 1.1.1 notebook's cell-by-cell renaming.
# Where the original_id is unique we map original_id → flat_name.
# For the duplicate sched_9910 we use the descriptive name to disambiguate.

_ORIGINAL_ID_TO_FLAT = {
    # Demographics
    "modified_dem_0110": "age",
    "dem_0500": "sex",
    "dem_0610": "height_inches",
    "dem_0700": "weight_pounds",
    "dem_0800": "bmi",
    "bthbts_0500": "num_people_in_house",
    "sched_9900": "sw_num_days_per_week",
    "sched_9920": "time_school_or_work_ends",  # will become sw_5pm_end_diff
    # Sleep Schedule - Work/School Nights
    "sched_0900": "bedtime_sw",
    "sched_0901": "bedtime_sw_varies",
    "sched_1000": "wakeup_sw",
    "sched_1001": "wakeup_sw_varies",
    "sched_2200": "latency_sw",
    "sched_2300": "total_slp_duration_sw",
    "sched_2500": "hrs_awake_night_sw",
    "sched_2600": "slp_quality_sw",
    "sched_2400": "num_awakens_night_sw",
    # Sleep Schedule - Non Work/School Nights
    "sched_1900": "bedtime_no_sw",
    "sched_1901": "bedtime_no_sw_varies",
    "sched_2000": "wakeup_no_sw",
    "sched_2001": "wakeup_no_sw_varies",
    "sched_3700": "latency_no_sw",
    "sched_3800": "total_slp_duration_no_sw",
    "sched_3900": "hrs_awake_night_no_sw",
    "sched_4100": "slp_quality_no_sw",
    "sched_4200": "amt_slp_fully_rested",
    "sched_4201": "never_feel_rested",
    # NOSE Survey
    "nose_0100": "nasal_congestion_stuffiness_nose",
    "nose_0200": "nasal_blockage_obstr_nose",
    "nose_0300": "troub_brth_nose",
    "nose_0400": "troub_slp_nose",
    "nose_0500": "not_enough_air_excercise_nose",
    # Household/Bed
    "bthbts_0100": "bed_partners",
    "bthbts_0300": "screen_before_bed_hrs",
    # Exercise/Activity (will be merged into exercise_amt_or_time)
    "soclhx_0501": "exercise_rarely_or_never",
    "soclhx_0600": "exercise_time_of_day",
    # Alcohol
    "soclhx_0701": "alcohol_consumption_rarely_or_never",
    "soclhx_0800": "alcohol_as_sleep_aid",
    # Caffeine
    "soclhx_0900": "daily_caffeine_servings",
    "soclhx_0901": "caffeine_consumption_rarely_or_never",
    "soclhx_1000": "hours_between_last_caffeine_and_bedtime",
    # Smoking
    "never_cigarette_smoker": "never_smoked",
    "former_cigarette_smoker": "former_smoker",
    "current_cigarette_smoker": "current_smoker",
    # Street Drugs
    "soclhx_1500": "street_drug_consume_status",
    # Napping (will be merged)
    "soclhx_0100": "nap_num",
    "soclhx_0101": "rarely_or_never_nap",
    "soclhx_0110": "nap_freq_period",
    "soclhx_0200": "usual_nap_duration",
    "soclhx_0300": "feel_refreshed_after_nap",
    "soclhx_0400": "easily_awake_after_nap",
    # OSA Symptoms
    "osa_0100": "heartburn_belching_after_bed_freq",
    "osa_0200": "heavy_sweat_during_sleep_freq",
    "osa_0300": "dry_irritated_eyes_freq",
    # Circadian
    "cir_0100": "routinely_travel_to_other_time_zones",
    "cir_0600": "horne_ostberg_morn_or_evening_type",
    "cir_0700": "rmeq_total_score",
    # PHQ-9
    "phq_0100": "little_interest_or_pleasure_freq_phq",
    "phq_0200": "feel_depressed_freq_phq",
    "phq_0300": "trouble_sleeping_or_too_much_sleep_freq_phq",
    "phq_0400": "feel_no_energy_freq_phq",
    "phq_0500": "poor_appetite_overeat_freq_phq",
    "phq_0600": "feel_bad_abt_yourself_freq_phq",
    "phq_0700": "trouble_focusing_freq_phq",
    "phq_0800": "slow_move_or_speak_freq_phq",
    "phq_0900": "thought_you_would_be_better_dead_freq_phq",
    "phq_1000": "phq_total_score",
    # GAD-7
    "gad_0100": "feeling_anxious_freq_gad",
    "gad_0200": "not_able_to_control_worrying_freq_gad",
    "gad_0300": "worry_too_much_diff_things_freq_gad",
    "gad_0400": "trouble_relaxing_freq_gad",
    "gad_0500": "cant_sit_still_freq_gad",
    "gad_0600": "easily_annoyed_freq_gad",
    "gad_0700": "feel_as_if_awful_might_happen_freq_gad",
    "gad_0800": "gad_total_score",
    # FSS
    "fss_0100": "lower_motivation_when_fati_fss",
    "fss_0200": "exercise_brings_fati_fss",
    "fss_0300": "i_am_easily_fati_fss",
    "fss_0400": "fati_interferes_with_phys_function_fss",
    "fss_0500": "fati_causes_freq_probs_for_me_fss",
    "fss_0600": "fati_prevents_sustained_phys_func_fss",
    "fss_0700": "fati_interferes_with_responsibilities_fss",
    "fss_0800": "fati_top_three_disabling_sympts_fss",
    "fss_0900": "fati_interferes_with_work_fam_social_fss",
    "fss_1000": "fss_total_score",
    # Diet
    "diet_0400": "eating_impact_alertness",
    "diet_0500": "feel_more_alert_if_skip_lunch",
    "diet_0600": "sleep_less_sound_if_skip_dinner",
    "diet_0700": "perception_of_weight",
    # Medical History (mdhx)
    "mdhx_0200": "prev_been_to_sleep_specialist",
    "mdhx_0400": "type_of_pap_device",
    "mdhx_5500": "trigger_for_slp_disorder_mdhx",
    "mdhx_5600": "sleep_aids_min_once_per_week",
    "mdhx_5700": "hypertension_mdhx",
    "mdhx_5710": "congestive_heart_failure_mdhx",
    "mdhx_5720": "cardiovascular_problem_other_mdhx",
    "mdhx_5800": "asthma_mdhx",
    "mdhx_5810": "chronic_obstructive_pulmonary_disease_mdhx",
    "mdhx_5820": "pulmonary_problem_other_mdhx",
    "mdhx_5900": "allergies_or_sinus_problems_mdhx",
    "mdhx_5910": "tonsillectomy_or_adenoidectomy_mdhx",
    "mdhx_5920": "nasal_jaw_or_apnea_surgery_mdhx",
    "mdhx_5950": "ear_nose_and_throat_problem_or_surgery_other_mdhx",
    "mdhx_6000": "dental_problems_mdhx",
    "mdhx_6100": "gastrointestinal_problem_or_surgery_mdhx",
    "mdhx_6200": "neurologic_problem_mdhx",
    "mdhx_6300": "hypercholesterolemia_mdhx",
    "mdhx_6310": "type_2_diabetes_mdhx",
    "mdhx_6320": "endocrine_or_metabolic_problem_mdhx",
    "mdhx_6400": "urologic_or_kidney_problem_mdhx",
    "mdhx_6500": "pain_or_fatigue_mdhx",
    "mdhx_6600": "psychiatric_or_mental_health_problem_mdhx",
    "mdhx_6700": "medical_problem_or_surgery_other_mdhx",
    "mdhx_1400": "oophorectomy_bilateral_mdhx",
    "mdhx_6900": "genetic_testing_mdhx",
    # Family History
    "famhx_0100": "family_history_of_insomnia_mdhx",
    "famhx_0200": "family_history_of_sleep_apnea_mdhx",
    "famhx_0300": "family_history_of_narcolepsy_mdhx",
    "famhx_0400": "family_history_of_restless_leg_syndrome_mdhx",
    "famhx_0500": "family_history_of_other_sleep_disorder_mdhx",
    "famhx_0600": "family_history_of_sleepwalking_mdhx",
    "famhx_0700": "family_history_of_fibromyalgia_or_chronic_fatigue_mdhx",
    "famhx_0800": "family_history_of_depression_mdhx",
    "famhx_0900": "family_history_of_anxiety_mdhx",
    "famhx_1000": "family_history_of_other_psychiatric_illness_mdhx",
    "famhx_1100": "family_history_of_psychiatric_treatment_mdhx",
    "famhx_1200": "family_history_of_death_during_sleep_mdhx",
    "famhx_1300": "num_full_siblings",
    # Parasomnias
    "par_0300": "num_times_eat_drink_dur_sleep",
    "par_0301": "num_times_eat_drink_dur_sleep_dont_know",
    "par_0310": "eat_drink_sleep_time_frame",
    "par_0400": "freq_teeth_grinding",
    "par_0700": "num_nightmares",
    "par_0701": "nightmares_never_or_dont_know",
    "par_0710": "nightmares_time_frame",
    "par_0900": "remember_dreams_times",
    "par_0901": "remember_dreams_never_or_dont_know",
    "par_0910": "remember_dreams_time_frame",
    # RLS (one-hot encoded by Stage 1, severity kept as-is)
    "rls_probability": "rls_probability",
    "rls_severity": "rls_severity_current",
    # MAP
    "map_0100": "loud_snoring_map",
    "map_0200": "frequent_wakenings_map",
    "map_0300": "snorting_gasping_map",
    "map_0400": "fall_asleep_at_work_map",
    "map_0500": "frequent_tossing_turning_map",
    "map_0600": "breathing_stops_map",
    "map_0700": "excessive_sleepiness_map",
    "map_0800": "morning_headache_map",
    "map_0900": "fall_asleep_driving_map",
    "map_1000": "cataplexy_days_per_week",
    "map_1100": "num_hypnogogic_hallus_days_per_week",
    "index_1": "map_index_1_apnea_score",
    "index_3": "map_index_3_excessive_daytime_sleepiness_",
    "index_4": "map_index_4_narcolepsy_like_symptoms_score",
    "map_lr": "map_likelihood_ration",
    "score": "map_score",
    # ISQ
    "isq_0100": "diff_falling_asleep_isq",
    "isq_0200": "difficulty_staying_asleep_isq",
    "isq_0300": "multiple_awakenings_isq",
    "isq_0400": "feel_sleep_not_sound_isq",
    "isq_0500": "feel_sleep_unrefreshing_isq",
    "isq_0600": "how_much_does_your_sleep_bother_you_isq",
    "isq_0700": "sleep_affected_work_isq",
    "isq_0800": "sleep_affected_your_social_life_isq",
    "isq_0900": "sleep_affected_other_important_parts_of_life_isq",
    "isq_1000": "sleep_made_you_irritable_isq",
    "isq_1100": "sleep_caused_trouble_concentrating_isq",
    "isq_1200": "sleep_made_you_fatigued_isq",
    "isq_1300": "how_sleepy_do_you_feel_during_the_day_isq",
    "isq_score": "meets_criteria_isq",
    # ISI
    "isi_0100": "diff_falling_asleep_isi",
    "isi_0200": "diff_staying_asleep_isi",
    "isi_0300": "problems_waking_up_too_early_isi",
    "isi_0400": "how_satisfied_with_curr_sleep_pattern_isi",
    "isi_0500": "how_noticeable_is_sleep_problem_impacting_quality_of_life_isi",
    "isi_0600": "how_worried_about_current_sleep_problem_isi",
    "isi_0700": "sleep_problem_intereferes_with_daily_functioning_isi",
    "isi_score": "isi_total_score",
    # SLPY
    "slpy_0100": "difficulty_staying_awake_during_the_day_number_of_times",
    "slpy_0101": "diff_staying_awake_during_day_never",
    "slpy_0110": "difficulty_staying_awake_during_the_day_time_frame",
    "slpy_0200": "sleep_attacks_number_of_times",
    "slpy_0201": "sleep_attacks_never",
    "slpy_0210": "sleep_attacks_time_frame",
    "slpy_0300": "perform_activities_without_awareness_when_sleepy_number_of_times",
    "slpy_0301": "perform_activities_without_awareness_when_sleepy_never",
    "slpy_0310": "perform_activities_without_awareness_when_sleepy_time_frame",
    "slpy_0400": "num_accident_or_near_miss_due_to_sleepiness",
    "slpy_0410": "last_occurance_accident_or_near_miss_due_to_sleepiness",
    # ESS
    "ess_0100": "ess_chance_of_dozing_sitting_and_reading",
    "ess_0200": "ess_chance_of_dozing_tv",
    "ess_0300": "ess_chance_of_dozing_inactive_public",
    "ess_0400": "ess_chance_of_dozing_car_passenger_hr",
    "ess_0500": "ess_chance_of_dozing_lying_down_in_afternoon_when_circumstances_permit",
    "ess_0600": "ess_chance_of_dozing_sitting_and_talking_to_someone",
    "ess_0700": "ess_chance_of_dozing_sitting_quietly_after_lunch_without_alcohol",
    "ess_0800": "ess_chance_of_dozing_in_a_car_while_stopped_for_few_minutes_in_traffic",
    "ess_0900": "ess_total_score",
    # Narcolepsy
    "narc_0050": "current_treated_for_narcolepsy",
    "narc_1900": "sleep_paralysis_frequency_score",
    "narc_2000": "hh_frequency_score",
    # FOSQ
    "fosq_0100": "difficulty_concentrating_fosq",
    "fosq_0200": "difficulty_remembering_fosq",
    "fosq_0300": "difficulty_operating_motor_vehicles_for_short_distances_fosq",
    "fosq_0400": "difficulty_operating_motor_vehicles_for_long_distances_fosq",
    "fosq_0500": "difficulty_visiting_family_or_friends_in_their_home_fosq",
    "fosq_0600": "relationships_with_family_or_friends_affected_fosq",
    "fosq_0700": "difficulty_watching_a_movie_fosq",
    "fosq_0800": "difficulty_being_active_in_evening_fosq",
    "fosq_0900": "difficulty_being_active_in_morning_fosq",
    "fosq_1000": "effect_on_desire_for_intimacy_or_sex_fosq",
    "fosq_1100": "fosq_summary_score",
    # AHI
    "ahi": "ahi",
}

# Disambiguation for duplicate sched_9910
_SCHED_9910_MAP = {
    "irregular_schedule": "irreg_sched",
    "time_school_or_work_starts": "time_school_or_work_starts",  # → sw_9am_start_diff
}

# ── Columns selected for the final factor analysis (from 2.1 cell 33) ──────

_FACTOR_COLUMNS = [
    "age",
    "bmi",
    "sex",
    "sw_9am_start_diff",
    "sw_5pm_end_diff",
    "nasal_congestion_stuffiness_nose",
    "nasal_blockage_obstr_nose",
    "troub_brth_nose",
    "troub_slp_nose",
    "not_enough_air_excercise_nose",
    "exercise_amt_or_time",
    "daily_caffeine_servings",
    "heartburn_belching_after_bed_freq",
    "heavy_sweat_during_sleep_freq",
    "dry_irritated_eyes_freq",
    "eating_impact_alertness",
    "never_smoked",
    "never_feel_rested",
    "nap_num",
    "feel_refreshed_after_nap",
    "easily_awake_after_nap",
    "feel_sleep_unrefreshing_isq",
    "feel_sleep_not_sound_isq",
    "latency_sw",
    "total_slp_duration_sw",
    "slp_quality_sw",
    "amt_slp_fully_rested",
    "usual_nap_duration",
    "map_index_4_narcolepsy_like_symptoms_score",
    "sleep_paralysis_frequency_score",
    "hh_frequency_score",
    "frequent_wakenings_map",
    "frequent_tossing_turning_map",
    "diff_falling_asleep_isq",
    "difficulty_staying_asleep_isq",
    "multiple_awakenings_isq",
    "hrs_awake_night_sw",
    "num_awakens_night_sw",
    "loud_snoring_map",
    "snorting_gasping_map",
    "fall_asleep_at_work_map",
    "breathing_stops_map",
    "excessive_sleepiness_map",
    "morning_headache_map",
    "fall_asleep_driving_map",
    "map_index_1_apnea_score",
    "map_index_3_excessive_daytime_sleepiness_",
    "map_likelihood_ration",
    "map_score",
    "ess_total_score",
    "difficulty_staying_awake_during_the_day_number_of_times",
    "diff_falling_asleep_isi",
    "diff_staying_asleep_isi",
    "problems_waking_up_too_early_isi",
    "how_satisfied_with_curr_sleep_pattern_isi",
    "how_noticeable_is_sleep_problem_impacting_quality_of_life_isi",
    "how_worried_about_current_sleep_problem_isi",
    "sleep_problem_intereferes_with_daily_functioning_isi",
    "isi_total_score",
    "sleep_affected_work_isq",
    "sleep_affected_your_social_life_isq",
    "sleep_affected_other_important_parts_of_life_isq",
    "sleep_made_you_irritable_isq",
    "sleep_caused_trouble_concentrating_isq",
    "sleep_made_you_fatigued_isq",
    "how_sleepy_do_you_feel_during_the_day_isq",
    "rmeq_total_score",
    "remember_dreams_times",
    "difficulty_concentrating_fosq",
    "difficulty_remembering_fosq",
    "difficulty_operating_motor_vehicles_for_short_distances_fosq",
    "difficulty_operating_motor_vehicles_for_long_distances_fosq",
    "difficulty_visiting_family_or_friends_in_their_home_fosq",
    "relationships_with_family_or_friends_affected_fosq",
    "difficulty_watching_a_movie_fosq",
    "difficulty_being_active_in_evening_fosq",
    "difficulty_being_active_in_morning_fosq",
    "effect_on_desire_for_intimacy_or_sex_fosq",
    # PHQ individual items (added in 2.0)
    "little_interest_or_pleasure_freq_phq",
    "feel_depressed_freq_phq",
    "trouble_sleeping_or_too_much_sleep_freq_phq",
    "feel_no_energy_freq_phq",
    "poor_appetite_overeat_freq_phq",
    "feel_bad_abt_yourself_freq_phq",
    "trouble_focusing_freq_phq",
    "slow_move_or_speak_freq_phq",
    "thought_you_would_be_better_dead_freq_phq",
    # GAD individual items
    "feeling_anxious_freq_gad",
    "not_able_to_control_worrying_freq_gad",
    "worry_too_much_diff_things_freq_gad",
    "trouble_relaxing_freq_gad",
    "cant_sit_still_freq_gad",
    "easily_annoyed_freq_gad",
    "feel_as_if_awful_might_happen_freq_gad",
    # FSS individual items
    "lower_motivation_when_fati_fss",
    "exercise_brings_fati_fss",
    "i_am_easily_fati_fss",
    "fati_interferes_with_phys_function_fss",
    "fati_causes_freq_probs_for_me_fss",
    "fati_prevents_sustained_phys_func_fss",
    "fati_interferes_with_responsibilities_fss",
    "fati_top_three_disabling_sympts_fss",
    "fati_interferes_with_work_fam_social_fss",
    # ESS individual items (added in 2.0)
    "ess_chance_of_dozing_in_a_car_while_stopped_for_few_minutes_in_traffic",
    "ess_chance_of_dozing_sitting_quietly_after_lunch_without_alcohol",
    "ess_chance_of_dozing_sitting_and_talking_to_someone",
    "ess_chance_of_dozing_lying_down_in_afternoon_when_circumstances_permit",
    "ess_chance_of_dozing_car_passenger_hr",
    "ess_chance_of_dozing_inactive_public",
    "ess_chance_of_dozing_tv",
    "ess_chance_of_dozing_sitting_and_reading",
    "screen_before_bed_hrs",
    # mdhx boolean columns
    "trigger_for_slp_disorder_mdhx",
    "prev_been_to_sleep_specialist",
    "family_history_of_psychiatric_treatment_mdhx",
    "family_history_of_other_psychiatric_illness_mdhx",
    "family_history_of_anxiety_mdhx",
    "family_history_of_depression_mdhx",
    "family_history_of_fibromyalgia_or_chronic_fatigue_mdhx",
    "family_history_of_sleepwalking_mdhx",
    "family_history_of_other_sleep_disorder_mdhx",
    "family_history_of_restless_leg_syndrome_mdhx",
    "family_history_of_narcolepsy_mdhx",
    "family_history_of_sleep_apnea_mdhx",
    "family_history_of_insomnia_mdhx",
    "genetic_testing_mdhx",
    "medical_problem_or_surgery_other_mdhx",
    "psychiatric_or_mental_health_problem_mdhx",
    "pain_or_fatigue_mdhx",
    "urologic_or_kidney_problem_mdhx",
    "endocrine_or_metabolic_problem_mdhx",
    "type_2_diabetes_mdhx",
    "hypercholesterolemia_mdhx",
    "neurologic_problem_mdhx",
    "gastrointestinal_problem_or_surgery_mdhx",
    "dental_problems_mdhx",
    "ear_nose_and_throat_problem_or_surgery_other_mdhx",
    "nasal_jaw_or_apnea_surgery_mdhx",
    "tonsillectomy_or_adenoidectomy_mdhx",
    "allergies_or_sinus_problems_mdhx",
    "pulmonary_problem_other_mdhx",
    "chronic_obstructive_pulmonary_disease_mdhx",
    "asthma_mdhx",
    "cardiovascular_problem_other_mdhx",
    "congestive_heart_failure_mdhx",
    "hypertension_mdhx",
    "oophorectomy_bilateral_mdhx",
    # Output
    "ahi",
]

# mdhx + famhx boolean columns to convert from bool → int
_MDHX_BOOL_COLS = [
    "trigger_for_slp_disorder_mdhx",
    "prev_been_to_sleep_specialist",
    "family_history_of_psychiatric_treatment_mdhx",
    "family_history_of_other_psychiatric_illness_mdhx",
    "family_history_of_anxiety_mdhx",
    "family_history_of_depression_mdhx",
    "family_history_of_fibromyalgia_or_chronic_fatigue_mdhx",
    "family_history_of_sleepwalking_mdhx",
    "family_history_of_other_sleep_disorder_mdhx",
    "family_history_of_restless_leg_syndrome_mdhx",
    "family_history_of_narcolepsy_mdhx",
    "family_history_of_sleep_apnea_mdhx",
    "family_history_of_insomnia_mdhx",
    "genetic_testing_mdhx",
    "medical_problem_or_surgery_other_mdhx",
    "psychiatric_or_mental_health_problem_mdhx",
    "pain_or_fatigue_mdhx",
    "urologic_or_kidney_problem_mdhx",
    "endocrine_or_metabolic_problem_mdhx",
    "type_2_diabetes_mdhx",
    "hypercholesterolemia_mdhx",
    "neurologic_problem_mdhx",
    "gastrointestinal_problem_or_surgery_mdhx",
    "dental_problems_mdhx",
    "ear_nose_and_throat_problem_or_surgery_other_mdhx",
    "nasal_jaw_or_apnea_surgery_mdhx",
    "tonsillectomy_or_adenoidectomy_mdhx",
    "allergies_or_sinus_problems_mdhx",
    "pulmonary_problem_other_mdhx",
    "chronic_obstructive_pulmonary_disease_mdhx",
    "asthma_mdhx",
    "cardiovascular_problem_other_mdhx",
    "congestive_heart_failure_mdhx",
    "hypertension_mdhx",
    "oophorectomy_bilateral_mdhx",
]


# ═══════════════════════════════════════════════════════════════════════════════
# Internal helpers
# ═══════════════════════════════════════════════════════════════════════════════


def _time_diff_in_hours(time1, time2):
    """Compute hours difference between two time objects."""
    dt1 = pd.to_datetime(time1, format="%H:%M:%S")
    dt2 = pd.to_datetime(time2, format="%H:%M:%S")
    return (dt1 - dt2).total_seconds() / 3600


def _flatten_multiindex(df: pd.DataFrame) -> pd.DataFrame:
    """Flatten a 3-level MultiIndex DataFrame to flat column names.

    Uses _ORIGINAL_ID_TO_FLAT for most columns and _SCHED_9910_MAP
    for the duplicate sched_9910 disambiguation.
    """
    flat_names = []
    for col in df.columns:
        descriptive, original, subset = col
        if original == "sched_9910":
            matched = False
            for desc_key, flat_name in _SCHED_9910_MAP.items():
                if desc_key in descriptive:
                    flat_names.append(flat_name)
                    matched = True
                    break
            if not matched:
                flat_names.append(original)
        elif original in _ORIGINAL_ID_TO_FLAT:
            flat_names.append(_ORIGINAL_ID_TO_FLAT[original])
        else:
            flat_names.append(original)

    result = df.copy()
    result.columns = flat_names
    return result


def _compute_work_schedule_diffs(df: pd.DataFrame) -> pd.DataFrame:
    """Compute sw_9am_start_diff and sw_5pm_end_diff from datetime columns."""
    nine_am = pd.to_datetime("09:00:00").time()
    five_pm = pd.to_datetime("17:00:00").time()

    if "time_school_or_work_starts" in df.columns:
        start_times = pd.to_datetime(
            df["time_school_or_work_starts"], errors="coerce"
        ).dt.time
        df["sw_9am_start_diff"] = start_times.apply(
            lambda x: _time_diff_in_hours(x, nine_am) if pd.notna(x) else np.nan
        )
        df = df.drop(columns=["time_school_or_work_starts"])

    if "time_school_or_work_ends" in df.columns:
        end_times = pd.to_datetime(
            df["time_school_or_work_ends"], errors="coerce"
        ).dt.time
        df["sw_5pm_end_diff"] = end_times.apply(
            lambda x: _time_diff_in_hours(x, five_pm) if pd.notna(x) else np.nan
        )
        df = df.drop(columns=["time_school_or_work_ends"])

    return df


def _recompute_map_lr(df: pd.DataFrame) -> pd.DataFrame:
    """Recompute map_likelihood_ration from map_score.

    TODO: investiage this and check online source datasets
    The raw dataset has a broken map_lr column (nearly all values are identical). MAYBE
    The correct likelihood ratio is: LR = score / (1 - score).
    """
    if "map_score" in df.columns and "map_likelihood_ration" in df.columns:
        df["map_likelihood_ration"] = df["map_score"] / (1 - df["map_score"])
    return df


def _merge_exercise(df: pd.DataFrame) -> pd.DataFrame:
    """Merge exercise_rarely_or_never + exercise_time_of_day → exercise_amt_or_time."""
    earlymorning_mapping = {
        0: "early morning",
        1: "late morning",
        2: "early afternoon",
        3: "late afternoon",
        4: "between dinner and bedtime",
        5: "varies",
    }

    if "exercise_time_of_day" in df.columns:
        df["exercise_time_of_day"] = df["exercise_time_of_day"].map(
            earlymorning_mapping
        )

    if "exercise_rarely_or_never" in df.columns:
        is_na = df["exercise_rarely_or_never"].isna()
        is_true = df["exercise_rarely_or_never"].fillna(0).astype(bool)

        df["exercise_rarely_or_never"] = np.where(
            is_na,
            np.nan,
            np.where(
                is_true, "rarely_or_never", df.get("exercise_time_of_day", np.nan)
            ),
        )

        if "exercise_time_of_day" in df.columns:
            df = df.drop(columns=["exercise_time_of_day"])
        df = df.rename(columns={"exercise_rarely_or_never": "exercise_amt_or_time"})

    return df


def _merge_caffeine(df: pd.DataFrame) -> pd.DataFrame:
    """If rarely_or_never caffeine, set daily_servings to 0."""
    if "caffeine_consumption_rarely_or_never" in df.columns:
        is_true = df["caffeine_consumption_rarely_or_never"].fillna(False).eq(True)
        is_na = df["daily_caffeine_servings"].isna() & ~is_true

        df["daily_caffeine_servings"] = np.where(
            is_true,
            0,
            np.where(is_na, np.nan, df["daily_caffeine_servings"]),
        )
        df = df.drop(columns=["caffeine_consumption_rarely_or_never"])

    return df


def _merge_freq_timeframe(
    df: pd.DataFrame,
    num_col: str,
    timeframe_col: str,
    never_col: str | None,
    result_col: str,
    timeframe_mapping: dict,
    never_label: str = "rarely or never",
) -> pd.DataFrame:
    """Merge a frequency count + time_frame into a single string column.

    Pattern used for naps, nightmares, dreams, sleepiness columns.
    """
    if timeframe_col in df.columns:
        df[timeframe_col] = df[timeframe_col].map(timeframe_mapping)

    if num_col in df.columns:
        freq_str = df[num_col].astype(str) + " " + df[timeframe_col].astype(str)
        df[num_col] = df[num_col].astype("string")
        df[num_col] = freq_str

        if timeframe_col in df.columns:
            df = df.drop(columns=[timeframe_col])

    if never_col and never_col in df.columns:
        df[num_col] = np.where(
            df[never_col].fillna(False),
            never_label,
            df[num_col],
        )
        df = df.drop(columns=[never_col])

    if result_col != num_col and num_col in df.columns:
        df = df.rename(columns={num_col: result_col})

    return df


_WPM_MAP = {0: "per week", 1: "per month", 2: "per year"}
_DAY_YEAR_MAP = {0: "Day", 1: "Week", 2: "Month", 3: "Year"}


def _merge_naps(df: pd.DataFrame) -> pd.DataFrame:
    """Merge nap_num + nap_freq_period → nap_num (string like '2 per week')."""
    return _merge_freq_timeframe(
        df,
        num_col="nap_num",
        timeframe_col="nap_freq_period",
        never_col=None,
        result_col="nap_num",
        timeframe_mapping=_WPM_MAP,
    )


def _merge_nightmares(df: pd.DataFrame) -> pd.DataFrame:
    """Merge num_nightmares + nightmares_time_frame → nightmares_freq."""
    return _merge_freq_timeframe(
        df,
        num_col="num_nightmares",
        timeframe_col="nightmares_time_frame",
        never_col="nightmares_never_or_dont_know",
        result_col="nightmares_freq",
        timeframe_mapping=_WPM_MAP,
        never_label="never or don't know",
    )


def _merge_sleepiness_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Merge the three SLPY frequency + time_frame columns."""
    pairs = [
        (
            "difficulty_staying_awake_during_the_day_number_of_times",
            "difficulty_staying_awake_during_the_day_time_frame",
            "diff_staying_awake_during_day_never",
        ),
        (
            "sleep_attacks_number_of_times",
            "sleep_attacks_time_frame",
            "sleep_attacks_never",
        ),
        (
            "perform_activities_without_awareness_when_sleepy_number_of_times",
            "perform_activities_without_awareness_when_sleepy_time_frame",
            "perform_activities_without_awareness_when_sleepy_never",
        ),
    ]
    for num_col, tf_col, never_col in pairs:
        if tf_col in df.columns:
            df[tf_col] = df[tf_col].map(_DAY_YEAR_MAP)

        if num_col in df.columns:
            freq_str = df[num_col].astype(str) + " " + df[tf_col].astype(str)
            df[num_col] = df[num_col].astype("string")
            df[num_col] = freq_str

            if tf_col in df.columns:
                df = df.drop(columns=[tf_col])

        if never_col in df.columns:
            df[num_col] = np.where(
                df[never_col].fillna(False),
                "rarely or never",
                df[num_col],
            )
            df = df.drop(columns=[never_col])

    return df


def _merge_dreams(df: pd.DataFrame) -> pd.DataFrame:
    """Merge remember_dreams_times + time_frame → remember_dreams_times (string)."""
    return _merge_freq_timeframe(
        df,
        num_col="remember_dreams_times",
        timeframe_col="remember_dreams_time_frame",
        never_col="remember_dreams_never_or_dont_know",
        result_col="remember_dreams_times",
        timeframe_mapping=_WPM_MAP,
        never_label="rarely or never",
    )


def _one_hot_encode_rls(df: pd.DataFrame) -> pd.DataFrame:
    """One-hot encode rls_probability into 4 boolean columns."""
    if "rls_probability" not in df.columns:
        return df

    dummies = pd.get_dummies(df["rls_probability"], prefix="rls")
    rename_map = {}
    for c in dummies.columns:
        val = c.replace("rls_", "")
        if val == "Likely":
            rename_map[c] = "rls_likely_curr"
        elif val == "Possible":
            rename_map[c] = "rls_possible_curr"
        elif val == "Unlikely":
            rename_map[c] = "rls_unlikely_curr"
        elif "possibly in past" in val.lower():
            rename_map[c] = "rls_unlikely_curr_probably_past"
    dummies = dummies.rename(columns=rename_map)
    df = pd.concat([df.drop(columns=["rls_probability"]), dummies], axis=1)
    return df


# ═══════════════════════════════════════════════════════════════════════════════
# 2.1 notebook encodings (applied after column selection)
# ═══════════════════════════════════════════════════════════════════════════════


def _encode_sex(df: pd.DataFrame) -> pd.DataFrame:
    df["sex"] = df["sex"].map({"M": 0, "F": 1})
    return df


def _encode_exercise(df: pd.DataFrame) -> pd.DataFrame:
    df["exercise_amt_or_time"] = df["exercise_amt_or_time"].map(
        {
            "rarely_or_never": 0,
            "between dinner and bedtime": 1,
            "late morning": 1,
            "early morning": 1,
            "early afternoon": 1,
            "late afternoon": 1,
        }
    )
    return df


def _encode_naps(df: pd.DataFrame) -> pd.DataFrame:
    """Encode nap_num string → binary frequent_naps (1 if per week, else 0)."""
    df["nap_num"] = np.where(
        df["nap_num"].astype(str).str.contains("per week", na=False),
        1,
        0,
    )
    df = df.rename(columns={"nap_num": "frequent_naps"})
    return df


def _encode_daytime_sleepiness(df: pd.DataFrame) -> pd.DataFrame:
    col = "difficulty_staying_awake_during_the_day_number_of_times"
    if col not in df.columns:
        return df
    df[col] = np.where(
        df[col].astype(str).str.contains("Day", na=False),
        1,
        np.where(
            df[col].astype(str).str.contains("Week", na=False),
            1,
            0,
        ),
    )
    df = df.rename(columns={col: "frequent_daytime_sleepiness"})
    return df


def _encode_dream_recall(df: pd.DataFrame) -> pd.DataFrame:
    """Encode remember_dreams_times → dream_recall_frequency (frequent/infrequent/rarely_or_never)."""
    col = "remember_dreams_times"
    if col not in df.columns:
        return df

    dream_count = df[col].str.extract(r"(\d+)").astype(float)
    dream_tf = df[col].str.extract(r"per\s(\w+)").iloc[:, 0]

    df[col] = np.where(
        (dream_count[0] >= 3)
        & ((dream_tf == "week") | ((dream_tf == "month") & (dream_count[0] >= 12))),
        "frequent",
        np.where(
            (dream_count[0] < 3)
            & ((dream_tf == "week") | ((dream_tf == "month") & (dream_count[0] < 12))),
            "infrequent",
            "rarely_or_never",
        ),
    )
    df = df.rename(columns={col: "dream_recall_frequency"})
    return df


def _convert_booleans(df: pd.DataFrame, columns: list[str]) -> pd.DataFrame:
    """Convert boolean columns to int (fillna False first)."""
    for col in columns:
        if col in df.columns:
            df[col] = df[col].fillna(0).astype(int)
    return df


def _replace_placeholders(df: pd.DataFrame) -> pd.DataFrame:
    """Replace -66 and -55 placeholder values with NA across all columns."""
    df = df.replace([-55, -66, -44], pd.NA)
    return df


def _impute(df: pd.DataFrame) -> pd.DataFrame:
    """Impute numeric columns with median, categorical with mode."""
    from sklearn.impute import SimpleImputer

    num_cols = df.select_dtypes(include=["int64", "float64", "Int32"]).columns
    cat_cols = df.select_dtypes(include=["object", "bool"]).columns

    if len(num_cols) > 0:
        median_imputer = SimpleImputer(strategy="median")
        df[num_cols] = median_imputer.fit_transform(df[num_cols])

    if len(cat_cols) > 0:
        mode_vals = df[cat_cols].mode().iloc[0]
        with pd.option_context("future.no_silent_downcasting", True):
            for col in cat_cols:
                df[col] = df[col].fillna(mode_vals[col]).infer_objects(copy=False)

    return df


def _one_hot_encode_dream_recall(df: pd.DataFrame) -> pd.DataFrame:
    """One-hot encode dream_recall_frequency, dropping first category."""
    from sklearn.preprocessing import OneHotEncoder

    col = "dream_recall_frequency"
    if col not in df.columns:
        return df

    ohe = OneHotEncoder(sparse_output=False, drop="first")
    encoded = ohe.fit_transform(df[[col]])
    cat_names = ohe.get_feature_names_out([col])
    encoded_df = pd.DataFrame(encoded, columns=cat_names, index=df.index)
    df = pd.concat([df.drop(columns=[col]), encoded_df], axis=1)
    return df


# ═══════════════════════════════════════════════════════════════════════════════
# Public API
# ═══════════════════════════════════════════════════════════════════════════════


def encode_features(df: pd.DataFrame) -> pd.DataFrame:
    """Stage 2: convert Stage 1 MultiIndex DataFrame into encoded flat DataFrame.

    Parameters
    ----------
    df : pd.DataFrame
        Stage 1 output with 3-level MultiIndex (descriptive, original, subset).

    Returns
    -------
    pd.DataFrame
        Flat DataFrame with encoded, imputed features ready for factor analysis.
        Contains the factor analysis feature columns plus 'ahi' as target.
    """
    df = df.copy()

    # Step 1: Flatten MultiIndex → flat column names
    df = _flatten_multiindex(df)

    # Step 2: Compute work schedule time diffs
    df = _compute_work_schedule_diffs(df)

    # Step 3: Recompute map_likelihood_ration from map_score (raw data is broken)
    df = _recompute_map_lr(df)

    # Step 4: One-hot encode RLS probability
    df = _one_hot_encode_rls(df)

    # Step 5: Merge compound columns
    df = _merge_exercise(df)
    df = _merge_caffeine(df)
    df = _merge_naps(df)
    df = _merge_nightmares(df)
    df = _merge_sleepiness_columns(df)
    df = _merge_dreams(df)

    # Step 5: Select factor analysis columns
    available = [c for c in _FACTOR_COLUMNS if c in df.columns]
    missing = [c for c in _FACTOR_COLUMNS if c not in df.columns]
    if missing:
        import warnings

        warnings.warn(f"Missing columns for factor analysis: {missing}")
    df = df[available]

    # Step 6: Encode categorical features
    df = _encode_sex(df)
    df = _encode_exercise(df)
    df = _encode_naps(df)
    df = _encode_daytime_sleepiness(df)
    df = _encode_dream_recall(df)

    # Step 7: Convert boolean columns to int
    df = _convert_booleans(df, ["never_smoked", "never_feel_rested"])
    df = _convert_booleans(df, _MDHX_BOOL_COLS)

    # Step 8: Drop rows missing AHI
    df = df.dropna(subset=["ahi"])

    # Step 9: Replace placeholder values
    df = _replace_placeholders(df)

    # Step 10: Impute
    df = _impute(df)

    # Step 11: One-hot encode dream_recall_frequency
    df = _one_hot_encode_dream_recall(df)

    return df


if __name__ == "__main__":
    from src.features.raw_data_loader import load_and_clean_raw

    raw = load_and_clean_raw(".")
    print(f"Stage 1 shape: {raw.shape}")

    encoded = encode_features(raw)
    print(f"Stage 2 shape: {encoded.shape}")
    print(f"Columns: {encoded.columns.tolist()}")
    print(f"Dtypes:\n{encoded.dtypes.value_counts()}")
    print(f"Nulls: {encoded.isnull().sum().sum()}")
    print(encoded.head())
