"""
Stage 1 transformer: loads raw STAGES data and applies the initial cleaning
steps from the 1.0-jp-initial-data-exploration notebook.

Produces a 3-level MultiIndex DataFrame (descriptive, original, subset)
with demographics columns combined/cleaned and datetime types applied.

generated by claude opus 4.6 based on the 1.0-jp-initial-data-exploration notebook,
with some adjustments for code organization and reusability.
"""

import pandas as pd
import numpy as np
from pathlib import Path

from src.utils.data_utils import add_multi_index, strip_text


# ── paths (relative to project root) ────────────────────────────────────────

RAW_DATASET = "data/raw/stages/datasets/stages-dataset-0.3.0.csv"
DATA_DICT = "data/raw/stages/datasets/stages-data-dictionary-0.3.0-variables.csv"
AHI_EXCEL = (
    "data/raw/stages/original/De-identified Data/"
    "PSG SRBD Variables/"
    "STAGESPSGKeySRBDVariables2020-08-29 Deidentified.xlsx"
)

# ── columns to drop from demographics (bias / redundancy) ───────────────────

_DEMOGRAPHICS_DROP_INITIAL = [
    "dem_0100",  # year of birth (age is present)
    "dem_0900",  # ethnicity (hispanic or latino)
    "dem_0910",  # ethnicity sub
    "dem_1000",  # race (main)
    "dem_1010",  # race (sub)
    "dem_1100",  # english as native language
    "dem_1120",  # proficiency in english
    "sched_0100",  # level of school
]

# columns consumed by the combined features, dropped after engineering
_DEMOGRAPHICS_DROP_AFTER_COMBINE = [
    "sched_0200",  # days_per_week_in_school
    "sched_0300",  # time_school_starts
    "sched_0700",  # work_start_time_current_shift
    "sched_0400",  # time_school_ends
    "sched_0800",  # work_end_time_current_shift
    "sched_0301",  # time_school_starts_varies
    "sched_0401",  # time_school_ends_varies
    "sched_0500",  # regular_or_irregular_work_schedule
    "sched_0510",  # do_you_work_a_split_shift
    "sched_0600",  # days_per_week_at_work
    "sched_1100",  # work_start_time_next_shift
    "sched_1200",  # work_end_time_next_shift
    "sched_1500",  # work_start_time_3rd_shift
    "sched_1501",  # work_start_time_no_3rd_shift
    "sched_1600",  # work_end_time_3rd_shift
    "sched_2100",  # how_often_change_work_shifts
    "dem_0600",  # height_in_feet (folded into inches)
]

# ── integer columns in demographics ─────────────────────────────────────────

_DEMOGRAPHICS_INT_COLS = [
    "modified_dem_0110",  # participants_age
    "dem_0610",  # height_in_inches
    "bthbts_0500",  # number of people in household
    "bthbts_0510",  # children ≤5
    "bthbts_0520",  # children 6-17
    "bthbts_0530",  # adults 18-59
    "bthbts_0540",  # adults ≥60
    "sched_9900",  # days_per_week_in_school_or_work (new)
]

# ── sleep patterns datetime columns ─────────────────────────────────────────

_SLEEP_PATTERNS_DT_COLS = [
    "sched_0900",  # in-bed time weeknights current shift
    "sched_1000",  # out-bed time weeknights current shift
    "sched_1300",  # in-bed time weeknights next shift
    "sched_1400",  # out-bed time weeknights next shift
    "sched_1700",  # in-bed time weeknights 3rd shift
    "sched_1800",  # out-bed time weeknights 3rd shift
    "sched_1900",  # in-bed time weekends
    "sched_2000",  # out-bed time weekends
]

# ── health datetime columns ─────────────────────────────────────────────────

_HEALTH_DT_COLS = [
    "soclhx_1000",  # caffeine last drink time
    "diet_0870",  # additional meal/snack time 5
    "diet_0860",  # additional meal/snack time 4
    "diet_0850",  # additional meal/snack time 3
    "diet_0840",  # additional meal/snack time 2
    "diet_0830",  # additional meal/snack time 1
    "diet_0820",  # usual dinner time
    "diet_0810",  # usual lunch time
    "diet_0800",  # usual breakfast time
]

# ── subset label assignments (from data-dictionary labels / folders) ────────

_LABEL_SUBSETS = {
    "parasomnias": [
        "hypnogogic_hallucinations",
        "bruxism",
        "sleep_paralysis",
        "nightmare",
        "sleepwalk",
    ],
    "sleep_patterns": [
        "sleep_latency",
        "sleep_quality",
        "sleep_satisfaction",
        "sleep_duration",
        "sleep_timing",
        "sleep_hygiene",
        "sleep_eat",
        "subject_sleepiness",
    ],
    "rls": ["rls_plms"],
    "narc": ["narcolepsy"],
    "insomnia": ["insomnia"],
}

_FOLDER_SUBSETS = {
    "demographics": ["Demographics", "Anthropometry"],
    "health": ["Health"],  # str.contains
    "medhx": ["Medical History"],  # str.startswith
    "sleep_questions": ["Sleep Questionnaires"],
    "sleep_treatment": ["Sleep Treatment"],
}


# ═══════════════════════════════════════════════════════════════════════════════
# Helper: build subset column lists from data dictionary
# ═══════════════════════════════════════════════════════════════════════════════


def _build_subset_column_lists(data_dict: pd.DataFrame):
    """Return dict  subset_name -> list[column_id]  (de-duplicated)."""

    fl = data_dict[["folder", "labels", "id"]].set_index("id")

    subsets: dict[str, list[str]] = {}

    # label-based subsets
    for name, labels in _LABEL_SUBSETS.items():
        mask = fl["labels"].isin(labels)
        subsets[name] = fl.loc[mask].index.tolist()

    # folder-based subsets
    # demographics + anthropometry
    dem_mask = fl["folder"].str.startswith("Demographics", na=False)
    anth_mask = fl["folder"].str.startswith("Anthropometry", na=False)
    subsets["demographics"] = fl.loc[dem_mask | anth_mask].index.tolist()

    # health (contains "Health")
    subsets["health"] = fl.loc[
        fl["folder"].str.contains("Health", na=False)
    ].index.tolist()

    # medical history
    subsets["medhx"] = fl.loc[
        fl["folder"].str.startswith("Medical History", na=False)
    ].index.tolist()

    # sleep questionnaires
    subsets["sleep_questions"] = fl.loc[
        fl["folder"].str.startswith("Sleep Questionnaires", na=False)
    ].index.tolist()

    # sleep treatment
    subsets["sleep_treatment"] = fl.loc[
        fl["folder"].str.startswith("Sleep Treatment", na=False)
    ].index.tolist()

    # de-duplicate (priority order matches notebook)
    seen: set[str] = set()
    dedup_order = [
        "parasomnias",
        "sleep_patterns",
        "demographics",
        "health",
        "medhx",
        "rls",
        "narc",
        "insomnia",
        "sleep_questions",
        "sleep_treatment",
    ]

    # first pass: remove health cols from sleep_patterns
    subsets["sleep_patterns"] = [
        c for c in subsets["sleep_patterns"] if c not in subsets["health"]
    ]
    # remove parasomnias from sleep_questions
    subsets["sleep_questions"] = [
        c for c in subsets["sleep_questions"] if c not in subsets["parasomnias"]
    ]
    # remove sleep_patterns from sleep_questions
    subsets["sleep_questions"] = [
        c for c in subsets["sleep_questions"] if c not in subsets["sleep_patterns"]
    ]
    # remove medhx from health
    subsets["health"] = [c for c in subsets["health"] if c not in subsets["medhx"]]
    # remove health from insomnia
    subsets["insomnia"] = [c for c in subsets["insomnia"] if c not in subsets["health"]]
    # remove rls, narc, insomnia from sleep_questions
    subsets["sleep_questions"] = [
        c for c in subsets["sleep_questions"] if c not in subsets["rls"]
    ]
    subsets["sleep_questions"] = [
        c for c in subsets["sleep_questions"] if c not in subsets["narc"]
    ]
    subsets["sleep_questions"] = [
        c for c in subsets["sleep_questions"] if c not in subsets["insomnia"]
    ]

    return subsets


# ═══════════════════════════════════════════════════════════════════════════════
# Helper: apply 3-level subset MultiIndex
# ═══════════════════════════════════════════════════════════════════════════════


def _apply_subset_multiindex(df, subset_col_lists):
    """Add a 3rd MultiIndex level ('subset') using the precomputed column lists."""
    original_cols = df.columns.get_level_values(1)
    labels = []
    for col in original_cols:
        assigned = False
        for subset_name, col_list in subset_col_lists.items():
            if col in col_list:
                labels.append(subset_name)
                assigned = True
                break
        if not assigned:
            labels.append("unassigned")

    new_columns = pd.MultiIndex.from_arrays(
        [
            df.columns.get_level_values(0),
            original_cols,
            labels,
        ],
        names=["descriptive", "original", "subset"],
    )
    df = df.copy()
    df.columns = new_columns
    return df


# ═══════════════════════════════════════════════════════════════════════════════
# Demographics feature engineering
# ═══════════════════════════════════════════════════════════════════════════════


def _engineer_demographics(df):
    """Apply all demographics transformations from the 1.0 notebook.

    Operates on a 2-level MultiIndex (descriptive, original) DataFrame
    that contains only the demographics subset columns.
    """
    # --- drop bias / redundancy columns ---
    to_drop = [col for col in df.columns if col[1] in _DEMOGRAPHICS_DROP_INITIAL]
    df = df.drop(columns=to_drop)

    # --- combined days_per_week_in_school_or_work (max of school / work) ---
    school_days = (
        df.xs("sched_0200", level=1, axis=1)
        if ("days_per_week_in_school", "sched_0200") in df.columns
        else None
    )
    work_days = (
        df.xs("sched_0600", level=1, axis=1)
        if ("days_per_week_at_work", "sched_0600") in df.columns
        else None
    )

    school_work_cols = [c for c in df.columns if c[1] in ("sched_0200", "sched_0600")]
    df[("days_per_week_in_school_or_work", "sched_9900")] = df[school_work_cols].max(
        axis=1
    )

    # --- irregular_schedule (max of variation flags) ---
    vary_cols = [
        c
        for c in df.columns
        if c[1] in ("sched_0301", "sched_0401", "sched_0500", "sched_0510")
    ]
    df[("irregular_schedule", "sched_9910")] = df[vary_cols].max(axis=1)

    # --- combined start / end times ---
    # convert individual times to datetime first
    for orig_id in ("sched_0300", "sched_0700", "sched_0400", "sched_0800"):
        matches = [c for c in df.columns if c[1] == orig_id]
        for c in matches:
            df[c] = pd.to_datetime(df[c], errors="coerce", format="%H:%M:%S")

    start_cols = [c for c in df.columns if c[1] in ("sched_0300", "sched_0700")]
    df[("time_school_or_work_starts", "sched_9910")] = df[start_cols].min(axis=1)

    end_cols = [c for c in df.columns if c[1] in ("sched_0400", "sched_0800")]
    df[("time_school_or_work_ends", "sched_9920")] = df[end_cols].max(axis=1)

    # --- height: fold feet into inches ---
    feet_col = [c for c in df.columns if c[1] == "dem_0600"]
    inches_col = [c for c in df.columns if c[1] == "dem_0610"]
    if feet_col and inches_col:
        df[inches_col[0]] = df[inches_col[0]] + (df[feet_col[0]] * 12)

    # --- drop consumed columns ---
    to_drop = [c for c in df.columns if c[1] in _DEMOGRAPHICS_DROP_AFTER_COMBINE]
    df = df.drop(columns=to_drop)

    # --- type conversions ---
    int_cols = [c for c in df.columns if c[1] in _DEMOGRAPHICS_INT_COLS]
    for c in int_cols:
        df[c] = df[c].astype("Int64")

    bool_cols = [c for c in df.columns if c[1] == "sched_9910" and "irregular" in c[0]]
    for c in bool_cols:
        df[c] = df[c].astype("boolean")

    return df


# ═══════════════════════════════════════════════════════════════════════════════
# Datetime conversions for sleep patterns and health subsets
# ═══════════════════════════════════════════════════════════════════════════════


def _convert_sleep_patterns_datetimes(df):
    """Convert sleep-pattern time columns to datetime64[ns]."""
    df = df.copy()
    for col in df.columns:
        if col[1] in _SLEEP_PATTERNS_DT_COLS:
            df[col] = pd.to_datetime(df[col], errors="coerce", format="%H:%M:%S")
    return df


def _convert_health_datetimes(df):
    """Convert health meal/caffeine time columns to datetime64[ns]."""
    df = df.copy()
    for col in df.columns:
        if col[1] in _HEALTH_DT_COLS:
            df[col] = pd.to_datetime(df[col], errors="coerce", format="%H:%M:%S")
    return df


# ═══════════════════════════════════════════════════════════════════════════════
# Public API
# ═══════════════════════════════════════════════════════════════════════════════


def load_and_clean_raw(project_root: str | Path = ".") -> pd.DataFrame:
    """Load the raw STAGES data and apply Stage-1 cleaning.

    Parameters
    ----------
    project_root : str or Path
        Path to the project root (parent of ``data/``).

    Returns
    -------
    pd.DataFrame
        Cleaned DataFrame with a 3-level MultiIndex
        (descriptive, original, subset).
    """
    root = Path(project_root)

    # ── 1. load raw data + data dictionary ──────────────────────────────────
    stages_raw = pd.read_csv(root / RAW_DATASET)
    data_dict = pd.read_csv(root / DATA_DICT)

    # build display-name mapping
    display_names = data_dict.set_index("id")["display_name"].to_dict()
    stripped = strip_text(list(display_names.values()))
    keys = list(display_names.keys())
    name_map = {keys[i]: stripped[i] for i in range(len(keys))}

    # add 2-level MultiIndex (descriptive, original)
    stages_mi = add_multi_index(stages_raw, name_map)

    # ── 2. build subset column lists from data dictionary ───────────────────
    subset_cols = _build_subset_column_lists(data_dict)

    # ── 3. add 3-level MultiIndex (descriptive, original, subset) ───────────
    stages_mi = _apply_subset_multiindex(stages_mi, subset_cols)

    # ── 4. load AHI target from Excel, merge on subject_code ────────────────
    output_df = pd.read_excel(root / AHI_EXCEL)
    output_df = output_df[["s_code", "ahi"]]
    output_df = output_df.rename(columns={"s_code": "subject_code"})

    desc_dict = {"subject_code": "identifier", "ahi": "apnea_hypopnea_index"}
    output_df = add_multi_index(output_df, desc_dict)

    # add subset level
    output_labels = ["output"] * len(output_df.columns)
    output_df.columns = pd.MultiIndex.from_arrays(
        [
            output_df.columns.get_level_values(0),
            output_df.columns.get_level_values(1),
            output_labels,
        ],
        names=["descriptive", "original", "subset"],
    )

    stages_mi = pd.concat([stages_mi, output_df], axis=1)
    stages_mi = stages_mi.drop(columns=[("identifier", "subject_code", "output")])

    # ── 5. drop unassigned columns, duplicates, all-NA rows ─────────────────
    if "unassigned" in stages_mi.columns.get_level_values("subset"):
        stages_mi = stages_mi.drop("unassigned", axis=1, level="subset")

    stages_mi = stages_mi.drop_duplicates()
    stages_mi = stages_mi.dropna(how="all")

    # ── 6. extract subsets and apply per-subset transformations ──────────────
    output_subset = stages_mi.xs("output", level="subset", axis=1)

    demographics_df = stages_mi.xs("demographics", level="subset", axis=1)
    demographics_df = _engineer_demographics(demographics_df)

    medhx_df = stages_mi.xs("medhx", level="subset", axis=1)
    para_df = stages_mi.xs("parasomnias", level="subset", axis=1)

    sleep_patterns_df = stages_mi.xs("sleep_patterns", level="subset", axis=1)
    sleep_patterns_df = _convert_sleep_patterns_datetimes(sleep_patterns_df)

    health_df = stages_mi.xs("health", level="subset", axis=1)
    health_df = _convert_health_datetimes(health_df)

    rls_df = stages_mi.xs("rls", level="subset", axis=1)
    narc_df = stages_mi.xs("narc", level="subset", axis=1)
    insomnia_df = stages_mi.xs("insomnia", level="subset", axis=1)
    slp_quest_df = stages_mi.xs("sleep_questions", level="subset", axis=1)
    slp_treat_df = stages_mi.xs("sleep_treatment", level="subset", axis=1)

    # ── 7. recombine with updated subset labels ─────────────────────────────
    # demographics columns may have changed (drops + new features)
    demographics_columns_new = demographics_df.columns.get_level_values(1).tolist()
    subset_cols["demographics"] = demographics_columns_new

    result = pd.concat(
        [
            demographics_df,
            medhx_df,
            para_df,
            sleep_patterns_df,
            health_df,
            rls_df,
            narc_df,
            insomnia_df,
            slp_quest_df,
            slp_treat_df,
            output_subset,
        ],
        axis=1,
    )

    # rebuild 3-level index on the recombined frame
    subset_cols["output"] = output_subset.columns.get_level_values(1).tolist()
    result = _apply_subset_multiindex(result, subset_cols)

    return result


if __name__ == "__main__":
    df = load_and_clean_raw(".")
    print(f"Shape: {df.shape}")
    print(f"Subsets: {df.columns.get_level_values('subset').unique().tolist()}")
    print(df.head())
